### ISSUE TITLE
bug into file ArrayChar.java

### ISSUE THREAD

**Issue by Kokoss74** [java54Telran/array-chars#1]
Current version ArrayChar.java contains bug:
` public ArrayChar(char[] array) {
	  this.array = array;
   }`
   
to fix:
`public ArrayChar(char[] array) {
		this.array = new char[array.length];
		for(int i = 0; i < array.length; i++) {
			this.array[i] = array[i];
		}
}`

**Comment by Yuragranovsky** [comment]
An object of an ArrayChar class must contain the copy of a given in the constructor array

**Comment by Yuragranovsky** [comment]
fixed in the last commit
